#!/bin/bash

if [ -z "$1" ]; then
    echo "Error. Uso: ./ejecutar_todo.sh <semilla>"
    exit 1
fi

SEMILLA=$1
REPETICIONES=50
ARCHIVO_SALIDA_IBEX35_H="resultados/archivo_ibex35_hist.csv"
ARCHIVO_SALIDA_SYP100_H="resultados/archivo_syp100_hist.csv"
ARCHIVO_SALIDA_SYP500_H="resultados/archivo_syp500_hist.csv"
ARCHIVO_SALIDA_IBEX35_T="resultados/archivo_ibex35_2025.csv"
ARCHIVO_SALIDA_SYP100_T="resultados/archivo_syp100_2025.csv"
ARCHIVO_SALIDA_SYP500_T="resultados/archivo_syp500_2025.csv"


# 1. IBEX
source configuraciones/ibex_35.conf
R1=$RUTA_ARCHIVO; E1=$EVALUACIONES; H_IN1=$FECHA_HISTORICA_INICIO; H_FI1=$FECHA_HISTORICA_FINAL; T_IN1=$FECHA_TEST_INICIO; T_FI1=$FECHA_TEST_FINAL; L1=$LO; H1=$HI

# 2. S&P 100
source configuraciones/syp_100.conf
R2=$RUTA_ARCHIVO; E2=$EVALUACIONES; H_IN2=$FECHA_HISTORICA_INICIO; H_FI2=$FECHA_HISTORICA_FINAL; T_IN2=$FECHA_TEST_INICIO; T_FI2=$FECHA_TEST_FINAL; L2=$LO; H2=$HI

# 3. S&P 500
source configuraciones/syp_500.conf
R3=$RUTA_ARCHIVO; E3=$EVALUACIONES; H_IN3=$FECHA_HISTORICA_INICIO; H_FI3=$FECHA_HISTORICA_FINAL; T_IN3=$FECHA_TEST_INICIO; T_FI3=$FECHA_TEST_FINAL; L3=$LO; H3=$HI

# 4. LA LLAMADA

./build/main \
    $R1 $E1 $H_IN1 $H_FI1 $T_IN1 $T_FI1 $L1 $H1 \
    $R2 $E2 $H_IN2 $H_FI2 $T_IN2 $T_FI2 $L2 $H2 \
    $R3 $E3 $H_IN3 $H_FI3 $T_IN3 $T_FI3 $L3 $H3 \
    $REPETICIONES $SEMILLA $ARCHIVO_SALIDA_IBEX35_H $ARCHIVO_SALIDA_SYP100_H $ARCHIVO_SALIDA_SYP500_H \
    $ARCHIVO_SALIDA_IBEX35_T $ARCHIVO_SALIDA_SYP100_T $ARCHIVO_SALIDA_SYP500_T

